# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

#github
github:
  history: https://github.com/Gss615/blog/commits/master/source/
  edit: https://github.com/Gss615/blog/edit/master/source/

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
  - category.ejs
  - tag
  - tagcloud
  - archive
  - recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category.ejs
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
#google_analytics:
#gauges_analytics:
favicon: /images/javascript-color.png
twitter:
google_plus:
fb_admins:
fb_app_id:




